In [1]:
import pandas as pd
import numpy as np
import config
from sqlalchemy import text
print(config.version)
print(config.connection_string)
pd.set_option('display.max_columns', None)

3.2.0.Dev
postgresql://postgres:sa@localhost/icip

In [2]:
pop = pd.read_sql("select * from iris.demo_pop", config.connection_string)
pop

,index,015,1519,2024,2529,3034,3539,4044,4549,5054,5559,6064,6569,7074,75+,all
0,Femmes,5586.000000,2073.000000,1939.00000,1945.000000,2060.000000,2205.000000,2241.000000,2096.000000,2283.000000,2251.000000,2222.000000,2093.000000,1991.000000,4342.000000,35326.0
1,Hommes,5861.000000,2214.000000,2023.00000,1943.000000,1999.000000,2104.000000,2130.000000,2042.000000,2233.000000,2157.000000,2073.000000,1855.000000,1679.000000,2965.000000,33279.0
2,Ensemble,11447.000000,4287.000000,3962.00000,3888.000000,4059.000000,4309.000000,4371.000000,4138.000000,4516.000000,4408.000000,4295.000000,3948.000000,3669.000000,7307.000000,68606.0
3,Proportion,0.166851,0.062487,0.05775,0.056671,0.059164,0.062808,0.063712,0.060315,0.065825,0.064251,0.062604,0.057546,0.053479,0.106507,1.0

In [3]:
damir = pd.read_sql("select * from apl.damir_age_stats where psp_spe_snds > 0 and psp_spe_snds <= 42", config.connection_string)
damir

      psp_spe_snds  ann  age_ben_snds        nb   total_nb     ratio
0                1   20             0  20006799  170874330  0.117085
1                1   20            20  17127019  170874330  0.100232
2                1   20            30  17833626  170874330  0.104367
3                1   20            40  18584273  170874330  0.108760
4                1   20            50  22067147  170874330  0.129143
...            ...  ...           ...       ...        ...       ...
1075            42   24            50    560449    3753047  0.149332
1076            42   24            60    653318    3753047  0.174077
1077            42   24            70    631355    3753047  0.168225
1078            42   24            80    352557    3753047  0.093939
1079            42   24            99      4575    3753047  0.001219

[1080 rows x 6 columns]

In [4]:
pop_iris = pd.read_sql(f"select * from iris.pop_iris limit 100", config.connection_string)
pop_iris.head(5)

,id,iris,com,typ_iris,lab_iris,p20_pop,p20_pop0002,p20_pop0305,p20_pop0610,p20_pop1117,p20_pop1824,p20_pop2539,p20_pop4054,p20_pop5564,p20_pop6579,p20_pop80p,p20_pop0014,p20_pop1529,p20_pop3044,p20_pop4559,p20_pop6074,p20_pop75p,p20_pop0019,p20_pop2064,p20_pop65p,p20_poph,p20_h0014,p20_h1529,p20_h3044,p20_h4559,p20_h6074,p20_h75p,p20_h0019,p20_h2064,p20_h65p,p20_popf,p20_f0014,p20_f1529,p20_f3044,p20_f4559,p20_f6074,p20_f75p,p20_f0019,p20_f2064,p20_f65p,c20_pop15p,c20_pop15p_cs1,c20_pop15p_cs2,c20_pop15p_cs3,c20_pop15p_cs4,c20_pop15p_cs5,c20_pop15p_cs6,c20_pop15p_cs7,c20_pop15p_cs8,c20_h15p,c20_h15p_cs1,c20_h15p_cs2,c20_h15p_cs3,c20_h15p_cs4,c20_h15p_cs5,c20_h15p_cs6,c20_h15p_cs7,c20_h15p_cs8,c20_f15p,c20_f15p_cs1,c20_f15p_cs2,c20_f15p_cs3,c20_f15p_cs4,c20_f15p_cs5,c20_f15p_cs6,c20_f15p_cs7,c20_f15p_cs8,p20_pop_fr,p20_pop_etr,p20_pop_imm,p20_pmen,p20_phormen
0,10010000,010010000,01001,Z,5,806,31.484312,26.911747,53.754190,77.438835,28.29368,142.616820,166.360700,121.071230,119.551506,38.516964,155.30615,97.169380,148.761020,191.372060,143.61626,69.775150,201.92662,446.00490,158.068470,410.48022,90.988625,46.333977,72.82183,96.274330,70.021620,34.039833,114.88084,222.006260,73.593124,395.51978,64.317520,50.835403,75.939190,95.097720,73.59463,35.735317,87.045790,223.99864,84.475350,658.13617,4.692272,42.491710,61.774240,102.402054,98.466286,122.293900,183.69410,42.321590,345.543430,4.692272,23.550990,33.105650,55.811996,18.770603,94.214615,101.147310,14.249990,312.59274,0,18.940722,28.668587,46.590054,79.695680,28.079285,82.546800,28.071602,796.56260,9.437408,17.78354,806,0
1,10020000,010020000,01002,Z,5,262,5.988437,12.166344,19.185204,34.218155,11.59541,40.038967,71.453835,23.341795,28.106495,15.905362,57.24225,33.095707,56.756393,56.376186,38.18473,20.344732,77.77466,140.21349,44.011856,137.36920,27.091105,22.862534,24.57981,31.677656,20.536348,10.621757,40.32649,72.476814,24.565908,124.63079,30.151142,10.233176,32.176586,24.698532,17.64838,9.722974,37.448174,67.73667,19.445948,186.55077,25.157904,5.093406,18.283657,28.526825,18.865522,19.794107,61.55114,9.278198,101.717735,14.971092,5.093406,13.499375,4.221177,4.493918,15.300190,39.354294,4.784281,84.83303,10,0.000000,4.784281,24.305649,14.371604,4.493918,22.196848,4.493918,260.98132,1.018681,2.76170,262,0
2,10040101,010040101,01004,H,1,1805,80.347440,44.940186,98.034460,132.206130,350.59598,415.759770,230.791730,168.521710,200.748000,83.431180,315.32584,586.317100,321.573700,215.646160,213.69093,152.822880,512.92680,1008.27057,284.179170,881.13257,168.958400,314.005000,159.43874,91.737490,113.319275,33.673622,272.78394,501.908140,106.440470,924.24410,146.367430,272.312070,162.134960,123.908680,100.37166,119.149254,240.142900,506.36246,177.738710,1516.05030,0.000000,22.987476,88.925750,226.880340,348.300200,245.558500,289.27402,294.124020,736.173700,0.000000,22.987476,58.862210,124.656930,108.548990,193.670720,119.348785,108.098600,779.87660,0,0.000000,30.063541,102.223404,239.751220,51.887787,169.925230,186.025420,1550.38730,254.989290,213.67561,1442,362
3,10040102,010040102,01004,H,1,3633,151.531800,133.872560,207.372440,257.669740,376.98596,800.137400,650.746400,411.843660,439.620640,203.356950,624.64890,817.918700,707.664800,607.301800,543.89386,331.709440,853.36070,2136.79930,642.977600,1831.40310,367.926120,436.120820,383.95010,316.515600,224.322680,102.567730,503.36760,1094.399800,233.635640,1801.73450,256.722800,381.797880,323.714700,290.786220,319.57120,229.141710,349.993130,1042.39940,409.341950,3008.48850,7.396541,96.871414,121.937770,427.660980,551.228100,609.075740,703.29175,491.026370,1463.476900,5.521550,70.383060,74.740320,247.228420,148.252120,454.491330,282.626950,180.233150,1545.01170,1,26.488360,47.197450,180.432560,402.975980,154.584380,420.664800,310.793240,3170.91100,462.226680,575.38983,3633,0
4,10040201,010040201,01004,H,1,4097,165.340970,169.880660,243.321690,360.778800,327.81744,875.897300,691.367700,405.417420,547.582100,310.324620,806.03480,837.867550,733.374150,644.476000,585.95290,490.023320,1011.85520,2227.96680,857.906740,1911.65250,372.595580,410.298220,374.48190,308.132780,247.900150,198.243900,481.75880,1100.451200,329.442600,2186.07620,433.439240,427.569300,358.892240,336.343230,338.05276,291.779420,530.096440,1127.51560,528.464100,3281.69400,0.000000,88.690890,189.187150,477.233980,563.328860,568.807200,914.04675,480.399300,1529.057100,0.000000,75.029900,124.313750,222.336010,166.690320,398.632700,384.854830,157.199600,1752.63700,0,13.660983,64.873405,254.897960,396.638520,170.174480,529.191900,323.199700,3690.08230,407.646420,424.02316,4009,87

In [5]:
cols = ["p20_pop0002","p20_pop0305","p20_pop0610",
        "p20_pop1117","p20_pop1824","p20_pop2539","p20_pop4054","p20_pop5564","p20_pop6579","p20_pop80p"]	
pop_iris = pop_iris[cols]
pop_iris.head(1)

,p20_pop0002,p20_pop0305,p20_pop0610,p20_pop1117,p20_pop1824,p20_pop2539,p20_pop4054,p20_pop5564,p20_pop6579,p20_pop80p
0,31.484312,26.911747,53.75419,77.438835,28.29368,142.61682,166.3607,121.07123,119.551506,38.516964

In [13]:
##### print(damir[damir["age_ben_snds"]==20]["ratio"])
props=pop.iloc[-1].to_dict()
print(props)
# /!\ 015 est en fait 014
def compute_overrepresentation(damir_dataset, year, psp_spe_snds):
    bb = 1 if psp_spe_snds==1 else 0
    damir = damir_dataset[damir_dataset["ann"]==year]
    damir = damir[damir["psp_spe_snds"]==psp_spe_snds]
    overs={"year":year, "psp_spe_snds":psp_spe_snds}
    overs["p0002"]=(damir[damir["age_ben_snds"]==0]["ratio"]*(3+bb*3)/20/(props["015"]*3/15)).iloc[0]
    overs["p0305"]=(damir[damir["age_ben_snds"]==0]["ratio"]*3/20/(props["015"]*3/15)).iloc[0]
    overs["p0610"]=(damir[damir["age_ben_snds"]==0]["ratio"]*(5-bb)/20/(props["015"]*5/15)).iloc[0]
    overs["p1117"]=(damir[damir["age_ben_snds"]==0]["ratio"]*(7-bb)/20/(props["015"]*4/15+props["1519"]*3/5)).iloc[0]
    overs["p1824"]=((damir[damir["age_ben_snds"]==0]["ratio"]*(2-bb)/20+damir[damir["age_ben_snds"]==20]["ratio"].iloc[0]*5/10)/(props["1519"]*2/5+props["2024"]*1)).iloc[0]
    overs["p2539"]=((damir[damir["age_ben_snds"]==20]["ratio"]*6/10+damir[damir["age_ben_snds"]==30]["ratio"].iloc[0]*10/10)/(props["2529"]*1+props["3034"]*1+props["3539"]*1)).iloc[0]
    overs["p4054"]=((damir[damir["age_ben_snds"]==40]["ratio"]*10/10+damir[damir["age_ben_snds"]==50]["ratio"].iloc[0]*5/10)/(props["4044"]*1+props["4549"]*1+props["5054"]*1)).iloc[0]
    overs["p5564"]=((damir[damir["age_ben_snds"]==50]["ratio"]*5/10+damir[damir["age_ben_snds"]==60]["ratio"].iloc[0]*5/10)/(props["5559"]*1+props["6064"]*1)).iloc[0]
    overs["p6579"]=((damir[damir["age_ben_snds"]==60]["ratio"]*5/10+damir[damir["age_ben_snds"]==70]["ratio"].iloc[0]*10/10)/(props["6569"]*1+props["7074"]*1+props["75+"]*5/20)).iloc[0]
    overs["p80p"]=((damir[damir["age_ben_snds"]==80]["ratio"]*10/10+damir[damir["age_ben_snds"]==99]["ratio"].iloc[0]*10/10)/(props["75+"]*15/20)).iloc[0]
    return overs
    
overs = compute_overrepresentation(damir, 20, 1)
overs

{'index': 'Proportion', '015': 0.16685129580503164, '1519': 0.06248724601346821, '2024': 0.05775005101594613, '2529': 0.05667142815497187, '3034': 0.05916392152289887, '3539': 0.06280791767483894, '4044': 0.06371162872052007, '4549': 0.06031542430691193, '5054': 0.0658251464886453, '5559': 0.0642509401510072, '6064': 0.0626038538903303, '6569': 0.05754598723143749, '7074': 0.053479287525872374, '75+': 0.10650671952890418, 'all': 1.0}

{'year': 20,
 'psp_spe_snds': 1,
 'p0002': 1.0525978036900725,
 'p0305': 0.5262989018450362,
 'p0610': 0.421039121476029,
 'p1117': 0.4284322951786844,
 'p1824': 0.6764168404306106,
 'p2539': 0.9208626436778214,
 'p4054': 0.912979487962459,
 'p5564': 1.0856822075370485,
 'p6579': 1.5691946082024983,
 'p80p': 1.8935730234028294}

In [22]:
def df_append_dict(df, dico):
    dico_df = pd.DataFrame([dico])
    return pd.concat([df, dico_df], ignore_index=True)

df = pd.DataFrame(columns=overs.keys())
df = df_append_dict(df, overs)
df

,year,psp_spe_snds,p0002,p0305,p0610,p1117,p1824,p2539,p4054,p5564,p6579,p80p
0,20,1,1.052598,0.526299,0.421039,0.428432,0.676417,0.920863,0.912979,1.085682,1.569195,1.893573